Repository wecode-bootcamp-korea/14-2nd-2.9cm-backend, pull requests merged in 2020-12, with the labels that each got.

#1 Add: 모델 작성
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201202_1557.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  store/__init__.py
  store/admin.py
  store/apps.py
  store/migrations/0001_initial.py
  store/migrations/__init__.py
  store/models.py
  store/tests.py
  store/views.py
  tv/__init__.py
  tv/admin.py
  tv/apps.py
  tv/migrations/0001_initial.py
  tv/migrations/0002_creator_user.py
  tv/migrations/__init__.py
  tv/models.py
  tv/tests.py
  tv/views.py
  twopointnine/settings.py
  twopointnine/urls.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 리뷰 요청

#3 ADD: 회원가입, 로그인, 로그인 확인 데코레이터 추가
  order/migrations/0003_auto_20201203_1254.py
  order/models.py
  store/migrations/0003_product_thumnail_url.py
  store/migrations/0004_enquiry_parent.py
  store/models.py
  twopointnine/urls.py
  user/migrations/0002_auto_20201203_1704.py
  user/models.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#5 ADD: 소셜로그인 기능 추가
  user/api_urls.py
  user/tests.py
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#6 MODIFY: 회원가입시 해당 유저의 엑세스 토큰 반환
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#9 [modify]수정사항 변경 및 코드 리팩토링
  .DS_Store
  .gitignore
  store/urls.py
  store/views.py
  twopointnine/urls.py
Labels: Status: Accepted

#10 ADD: 핸드폰 인증 기능 추가, 본인인증 성공시 유저 상세정보 저장기능 추가
  user/api_urls.py
  user/migrations/0003_phoneauth.py
  user/migrations/0004_auto_20201206_2352.py
  user/models.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: Status: 리뷰 요청

#11 [modify]검색기능 추가 구현 및 페이지 네이션
  store/views.py
Labels: Status: 리뷰 요청

#8 cart view post,get 구현/ tests.py 구현
  .vscode/settings.json
  order/tests.py
  order/urls.py
  order/views.py
  twopointnine/urls.py
Labels: Status: 리뷰 요청

#16 [MODIFY] 코드 리팩토링
  store/views.py
Labels: Status: 리뷰 요청

#15 [ADD]productdetail GET /review POST GET
  Dockerfile
  order/tests.py
  requirements.txt
  store/tests.py
  store/urls.py
  store/views.py
  user/models.py
Labels: Status: 리뷰 요청

#14 [ADD] cart DELETE
  order/views.py
Labels: Status: 수정 요청
